# Generated by Django 3.1.4 on 2021-01-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GebruikersRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name_plural': 'gebruikersrollen',
            },
        ),
    ]
