CREATE TABLE IF NOT EXISTS "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "auth_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_user_groups_user_id_group_id_94350c0c_uniq" ON "auth_user_groups" ("user_id", "group_id");
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
CREATE UNIQUE INDEX "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" ON "auth_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
CREATE TABLE IF NOT EXISTS "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "action_time" datetime NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0));
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE TABLE IF NOT EXISTS "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE TABLE IF NOT EXISTS "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE TABLE IF NOT EXISTS "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "auth_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "first_name" varchar(150) NOT NULL);
CREATE TABLE IF NOT EXISTS "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE TABLE IF NOT EXISTS "vault_hierarchicallink" ("link_ptr_id" integer NOT NULL PRIMARY KEY REFERENCES "vault_link" ("id") DEFERRABLE INITIALLY DEFERRED, "extra" text NULL);
CREATE TABLE IF NOT EXISTS "vault_nonhistorisedlink" ("link_ptr_id" integer NOT NULL PRIMARY KEY REFERENCES "vault_link" ("id") DEFERRABLE INITIALLY DEFERRED, "extra" text NULL);
CREATE TABLE IF NOT EXISTS "vault_sameaslink" ("link_ptr_id" integer NOT NULL PRIMARY KEY REFERENCES "vault_link" ("id") DEFERRABLE INITIALLY DEFERRED, "extra" text NULL);
CREATE TABLE IF NOT EXISTS "vault_link_hubs" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "link_id" integer NOT NULL REFERENCES "vault_link" ("id") DEFERRABLE INITIALLY DEFERRED, "hub_id" integer NOT NULL REFERENCES "vault_hub" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "vault_link_hubs_link_id_hub_id_0d7e59d0_uniq" ON "vault_link_hubs" ("link_id", "hub_id");
CREATE INDEX "vault_link_hubs_link_id_8ddb4f37" ON "vault_link_hubs" ("link_id");
CREATE INDEX "vault_link_hubs_hub_id_a9df7245" ON "vault_link_hubs" ("hub_id");
CREATE TABLE IF NOT EXISTS "project_project" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(40) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS "vault_hub_projects" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "hub_id" integer NOT NULL REFERENCES "vault_hub" ("id") DEFERRABLE INITIALLY DEFERRED, "project_id" integer NOT NULL REFERENCES "project_project" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE UNIQUE INDEX "vault_hub_projects_hub_id_project_id_48c9392c_uniq" ON "vault_hub_projects" ("hub_id", "project_id");
CREATE INDEX "vault_hub_projects_hub_id_6c2e5813" ON "vault_hub_projects" ("hub_id");
CREATE INDEX "vault_hub_projects_project_id_cd670613" ON "vault_hub_projects" ("project_id");
CREATE TABLE IF NOT EXISTS "vault_hubattribute" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(40) NOT NULL UNIQUE, "data_type" varchar(40) NOT NULL, "isSequence" bool NOT NULL, "hub_id" integer NOT NULL REFERENCES "vault_hub" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE IF NOT EXISTS "vault_linkattribute" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(40) NOT NULL UNIQUE, "data_type" varchar(40) NOT NULL, "isForeignkey" bool NOT NULL, "link_id" integer NOT NULL REFERENCES "vault_link" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "vault_hubattribute_hub_id_0a8842a1" ON "vault_hubattribute" ("hub_id");
CREATE INDEX "vault_linkattribute_link_id_ccf6287e" ON "vault_linkattribute" ("link_id");
CREATE TABLE IF NOT EXISTS "vault_satattribute" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(40) NOT NULL UNIQUE, "data_type" varchar(40) NOT NULL, "isForeignkey" bool NOT NULL, "satellite_id" integer NOT NULL REFERENCES "vault_satellite" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "vault_satattribute_satellite_id_fa8d5061" ON "vault_satattribute" ("satellite_id");
CREATE TABLE IF NOT EXISTS "vault_satellite" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(40) NOT NULL UNIQUE, "hub_id" integer NULL REFERENCES "vault_hub" ("id") DEFERRABLE INITIALLY DEFERRED, "link_id" integer NULL REFERENCES "vault_link" ("id") DEFERRABLE INITIALLY DEFERRED, "subtype" varchar(3) NOT NULL);
CREATE INDEX "vault_satellite_hub_id_4a6296c3" ON "vault_satellite" ("hub_id");
CREATE INDEX "vault_satellite_link_id_82f311ec" ON "vault_satellite" ("link_id");
CREATE TABLE IF NOT EXISTS "vault_hub" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(40) NOT NULL UNIQUE, "omschrijving" text NOT NULL, "toelichting" text NOT NULL, "isStubHub" bool NOT NULL);
CREATE TABLE IF NOT EXISTS "vault_link" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(40) NOT NULL UNIQUE, "omschrijving" text NOT NULL, "links_id" integer NULL REFERENCES "vault_link" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "vault_link_links_id_ff3b1da6" ON "vault_link" ("links_id");
CREATE TABLE IF NOT EXISTS "glossary_context" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(60) NOT NULL);
CREATE TABLE IF NOT EXISTS "glossary_domein" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(60) NOT NULL);
CREATE TABLE IF NOT EXISTS "glossary_termtype" ("naam" varchar(20) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS "glossary_subdomein" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "naam" varchar(60) NOT NULL, "domein_id" integer NULL REFERENCES "glossary_domein" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE INDEX "glossary_subdomein_domein_id_51c970cc" ON "glossary_subdomein" ("domein_id");
CREATE TABLE IF NOT EXISTS "glossary_term" ("id" varchar(20) NOT NULL PRIMARY KEY, "context_id" integer NULL REFERENCES "glossary_context" ("id") DEFERRABLE INITIALLY DEFERRED, "termType_id" varchar(20) NULL REFERENCES "glossary_termtype" ("naam") DEFERRABLE INITIALLY DEFERRED, "definitie" text NULL, "toelichting" text NULL, "domein_id" integer NULL REFERENCES "glossary_domein" ("id") DEFERRABLE INITIALLY DEFERRED, "eenheid" varchar(50) NOT NULL, "synoniem" varchar(40) NOT NULL, "subdomein_id" integer NULL REFERENCES "glossary_subdomein" ("id") DEFERRABLE INITIALLY DEFERRED, "naam" varchar(40) NOT NULL);
CREATE INDEX "glossary_term_context_id_a274c159" ON "glossary_term" ("context_id");
CREATE INDEX "glossary_term_termType_id_547341e9" ON "glossary_term" ("termType_id");
CREATE INDEX "glossary_term_domein_id_7f417e79" ON "glossary_term" ("domein_id");
CREATE INDEX "glossary_term_subdomein_id_178f4a99" ON "glossary_term" ("subdomein_id");
