# Generated by Django 3.1.4 on 2020-12-23 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_auto_20201223_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.context'),
        ),
        migrations.AddField(
            model_name='term',
            name='termType',
            field=models.CharField(choices=[('BEGRIP', 'Begrip'), ('DEFINITIE', 'DEFINITIE')], default='BEGRIP', max_length=10),
        ),
    ]
