# Generated by Django 3.1.4 on 2020-12-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_auto_20201223_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='definitie',
            field=models.TextField(null=True),
        ),
    ]
