# Generated by Django 3.1.4 on 2020-12-23 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_term_definitie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='toelichting',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='context',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='glossary.context'),
        ),
        migrations.AddField(
            model_name='term',
            name='domein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='glossary.domein'),
        ),
    ]
