# Generated by Django 3.1.4 on 2020-12-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0005_auto_20201223_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermType',
            fields=[
                ('naam', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ('naam',)},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ('naam',)},
        ),
        migrations.AlterField(
            model_name='term',
            name='termType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='glossary.termtype'),
        ),
    ]
