# Generated by Django 3.1.4 on 2020-12-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0007_auto_20201223_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='definitie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='toelichting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
