# Generated by Django 3.1.4 on 2020-12-23 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0008_auto_20201223_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='glossary.context'),
        ),
        migrations.AlterField(
            model_name='term',
            name='domein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='glossary.domein'),
        ),
        migrations.AlterField(
            model_name='term',
            name='subdomein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='glossary.subdomein'),
        ),
        migrations.AlterField(
            model_name='term',
            name='termType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='glossary.termtype'),
        ),
    ]
