# Generated by Django 3.1.4 on 2020-12-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0009_auto_20201223_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='naam',
            field=models.CharField(max_length=40),
        ),
    ]
