# Generated by Django 3.1.4 on 2020-12-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0010_auto_20201223_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ('naam',), 'verbose_name_plural': 'contexten'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ('naam',), 'verbose_name_plural': 'termen'},
        ),
    ]
