# Generated by Django 3.1.4 on 2020-12-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0011_auto_20201223_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='eenheid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='synoniem',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
