# Generated by Django 3.1.4 on 2021-01-07 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('glossary', '0014_auto_20210107_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.context'),
        ),
        migrations.AlterField(
            model_name='term',
            name='domein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.domein'),
        ),
        migrations.AlterField(
            model_name='term',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='term',
            name='subdomein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='glossary.subdomein'),
        ),
        migrations.AlterField(
            model_name='term',
            name='termType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.termtype'),
        ),
    ]
