# Generated by Django 3.1.4 on 2021-01-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0015_auto_20210107_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.context'),
        ),
        migrations.AlterField(
            model_name='term',
            name='domein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.domein'),
        ),
        migrations.AlterField(
            model_name='term',
            name='subdomein',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='glossary.subdomein'),
        ),
    ]
