# Generated by Django 3.1.4 on 2021-01-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0017_auto_20210107_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='contactpersonen',
        ),
    ]
