# Generated by Django 3.1.4 on 2020-12-14 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': 'projecten'},
        ),
    ]
