# Generated by Django 3.1.4 on 2020-12-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchicalLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.link')),
                ('extra', models.TextField(blank=True, null=True)),
            ],
            bases=('vault.link',),
        ),
        migrations.CreateModel(
            name='NonHistorisedLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.link')),
                ('extra', models.TextField(blank=True, null=True)),
            ],
            bases=('vault.link',),
        ),
        migrations.CreateModel(
            name='SameAsLink',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vault.link')),
                ('extra', models.TextField(blank=True, null=True)),
            ],
            bases=('vault.link',),
        ),
        migrations.AddField(
            model_name='link',
            name='hubs',
            field=models.ManyToManyField(to='vault.Hub'),
        ),
        migrations.AddField(
            model_name='link',
            name='omschrijving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='hub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vault.hub'),
        ),
    ]
