# Generated by Django 3.1.4 on 2020-12-14 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_auto_20201214_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='hub',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vault.hub'),
        ),
    ]
