# Generated by Django 3.1.4 on 2020-12-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_auto_20201214_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='hub',
            name='projects',
            field=models.ManyToManyField(to='vault.Project'),
        ),
    ]
