# Generated by Django 3.1.4 on 2020-12-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('vault', '0005_auto_20201214_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='hub',
            name='projects',
            field=models.ManyToManyField(to='project.Project'),
        ),
    ]
