# Generated by Django 3.1.4 on 2020-12-14 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0008_link_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vault.link'),
        ),
    ]
