# Generated by Django 3.1.4 on 2020-12-14 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_satellite_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hub',
            options={'ordering': ('naam',)},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('naam',)},
        ),
        migrations.AlterModelOptions(
            name='satellite',
            options={'ordering': ('naam',)},
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40, unique=True)),
                ('data_type', models.CharField(max_length=40, unique=True)),
                ('isForeignkey', models.BooleanField(default=False, verbose_name='foreign key?')),
                ('hubs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.hub')),
            ],
        ),
    ]
