# Generated by Django 3.1.4 on 2020-12-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0010_auto_20201214_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='hubs',
            new_name='hub',
        ),
    ]
