# Generated by Django 3.1.4 on 2020-12-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0011_auto_20201214_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='isSequence',
            field=models.BooleanField(default=False, verbose_name='sequence_id?'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
