# Generated by Django 3.1.4 on 2020-12-14 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_auto_20201214_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40, unique=True)),
                ('data_type', models.CharField(blank=True, max_length=40)),
                ('isSequence', models.BooleanField(default=False, verbose_name='sequence_id?')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.hub')),
            ],
        ),
        migrations.CreateModel(
            name='LinkAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40, unique=True)),
                ('data_type', models.CharField(blank=True, max_length=40)),
                ('isForeignkey', models.BooleanField(default=False, verbose_name='foreign key?')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.link')),
            ],
        ),
        migrations.DeleteModel(
            name='Attribute',
        ),
    ]
