# Generated by Django 3.1.4 on 2020-12-14 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_auto_20201214_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=40, unique=True)),
                ('data_type', models.CharField(blank=True, max_length=40)),
                ('isForeignkey', models.BooleanField(default=False, verbose_name='foreign key?')),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vault.satellite')),
            ],
        ),
    ]
