# Generated by Django 3.1.4 on 2020-12-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_satattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='omschrijving',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hub',
            name='toelichting',
            field=models.TextField(blank=True, default=''),
        ),
    ]
