# Generated by Django 3.1.4 on 2020-12-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_auto_20201214_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hubattribute',
            options={'ordering': ('naam',), 'verbose_name': 'Attribuut (Hub)', 'verbose_name_plural': 'Attributen (Hub)'},
        ),
        migrations.AlterModelOptions(
            name='linkattribute',
            options={'ordering': ('naam',), 'verbose_name': 'Attribuut (Link)', 'verbose_name_plural': 'Attributen (Link)'},
        ),
        migrations.AlterModelOptions(
            name='satattribute',
            options={'ordering': ('naam',), 'verbose_name': 'Attribuut (Sat)', 'verbose_name_plural': 'Attributen (Sat)'},
        ),
        migrations.AddField(
            model_name='satellite',
            name='subtype',
            field=models.CharField(choices=[('MAS', 'Multi-Active'), ('EFF', 'Effectivity'), ('SYS', 'System-Driven')], default='SYS', max_length=3),
        ),
    ]
