# Generated by Django 3.1.4 on 2020-12-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0016_auto_20201215_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='isStubHub',
            field=models.BooleanField(default=False, verbose_name='stub-hub?'),
        ),
        migrations.AlterField(
            model_name='link',
            name='omschrijving',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
