# Generated by Django 3.1.4 on 2020-12-23 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0017_auto_20201215_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hubattribute',
            options={'ordering': ('-isSequence', 'naam'), 'verbose_name': 'Attribuut (Hub)', 'verbose_name_plural': 'Attributen (Hub)'},
        ),
    ]
